name: Security Scan and Docker Build
on:
  push:
    branches:
      - 'v[1-9]+\\.[0-9]+'

# env:
#   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set timezone
      run: |
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL,HIGH'

    - name: Print Trivy Scan
      run: cat trivy-results.txt

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-table@v2
      with:
        table_file: 'trivy-results.txt'

  build-and-push-docker:
    needs: [security-scan]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set timezone
      run: |
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/cleverest/test:$(date +%Y%m%d.%H.%M) .
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push docker.io/cleverest/test:$(date +%Y%m%d.%H.%M)
        echo yes
